### ISSUE TITLE
v4.6.0 doesn't mean it as well as v6.7.0

### ISSUE THREAD

**Issue by 462960** [nodejs/LTS#142]
Please, is there any explanation:
1) Installing v4.6.0 I have 2.15.9 http://clip2net.com/s/3CUWCiB
2) Installing v6.7.0  I have 3.10.3 http://clip2net.com/s/3CUPV38

Of course, all has been taken here https://nodejs.org/en/

**Comment by ErisDS** [comment]
Hi there @462960!

I'm not 100% clear on what you're asking, however, I think what's causing your confusion is that you're outputting the `npm` version, rather than the `node` version?

If you try doing `node -v` instead of `npm -v` you should see the version numbers that you expect. `npm` and `node` are two different things :)

**Comment by Fishrock123** [comment]
`node` v4.x comes with `npm` v2.x.
`node` v6.x comes with `npm` v3.x.

Node and npm are separate projects: https://nodejs.org/en/, https://www.npmjs.com/

**Comment by 462960** [comment]
Thanks a lot. I've been using npm command thinking it's Node itself.
Definitely, I have to learn about Node vs npm.
