### ISSUE TITLE
I can't install any module 

### ISSUE THREAD

**Issue by karangoswami31** [nodejs/LTS#148]
>  npm install -g bower
>npm install -g polymer-cli

i can't install any module facinng error below

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bower"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE

npm ERR! unable to verify the first certificate
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\karan\npm-debug.log

**Comment by bnoordhuis** [comment]
Can you post your question over at https://github.com/nodejs/help/issues?  Thanks.

**Comment by karangoswami31** [comment]
why you closed it  i am facing issue @bnoordhuis bnoordhuis

**Comment by TheAlphaNerd** [comment]
@karangoswami31 the issue was closed because this repo is specifically for our LTS release process, not for generic help. If you open an issue on https://github.com/nodejs/help/issues someone will be able to help you

fwiw it looks like a networking issue, are you behind a firewall or anything like that? That would be useful information to include in the issue report on help

**Comment by karangoswami31** [comment]
it's not like any Firwarell or networking issue
