### ISSUE TITLE
Should we move to a 3 week cadence

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/LTS#173]
~~Hey All. There is a meeting scheduled today but I think it makes sense to push it as many participants are off for the holidays. Are people open to pushing the meeting one week and offsetting future meeting accordingly? ~~

I would also like to suggest that we move to a  3 week cadence, I don't feel that we need bi-weekly anymore.

Thoughts?

edit: I was unaware that today was a holiday when I suggested running the meeting today. Due to this and the fact that no one responded we should keep the meeting as next week. I would still like to discuss a 3 week cadence though.

**Comment by hbetts** [comment]
Though I'm not an LTS member, but someone just interested in attending the meetings, I'm fine with delaying yesterday's meeting until next week. Also, I would be fine with out-right canceling it since there will be numerous occasions in the future where this decision will need to be made, and a known, long-term meeting schedule may (in my opinion) have greater benefit than a single meeting.

My only concern with a 3-week cadence, is what impact it will have on reacting to community needs and getting fixes and enhancements into LTS releases promptly. In particular, I have an interest in the SSL cert enhancement. My hope is that it will ship with the next Node release (which I believe is a minor release in January). Then there's the ~2 week "in the wild' period before it can be incorporated into an LTS release. Would a 3-week cadence negatively effect the ability for the LTS group to turn around getting those enhancements into LTS releases? 

That's just my input and thoughts on the matter.

**Comment by TheAlphaNerd** [comment]
@hbetts the three week cadence would have no affect on things landing in the community. The only things that require the lts group to discuss are semver minor changes. Those happen fairly infrequently and one meeting is usually enough to handle a multi month backlog. 

My personal concern is that there has been so few topics to discuss that we have ended up cancelling meetings, one cancelled meeting means a 4 week gap. A 3 week cadence will likely involve more meetings, as un-intuitive as that is.

**Comment by mhdawson** [comment]
3 weeks makes sense to me. What is the target for the next meeting ? I don't see an issue for yesterday (which was a holiday for us as well).

**Comment by MylesBorins** [comment]
current plan would be next Monday

**Comment by mhdawson** [comment]
Monday the 9th works for me.

**Comment by mhdawson** [comment]
+1

**Comment by MylesBorins** [comment]
It has been decided!
