### ISSUE TITLE
Charter this

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/LTS#48]
As stated in https://github.com/nodejs/node/issues/3454#issuecomment-149690084, we should write a charter and get the TSC to ratify this group, it's about time. :)

**Comment by Fishrock123** [comment]
Hmmm, looks like some WGs only have a bit in core's [WORKING_GROUPS.md](https://github.com/nodejs/node/blob/master/WORKING_GROUPS.md) and don't have their own `GOVERNANCE.md` file The website does.

cc @mikeal

**Comment by mikeal** [comment]
Governance is pretty loose in WGs prior to them being chartered, but all chartered WGs should document their governance. Also, *any* repo we contribute code to **MUST** have a CONTRIBUTING file that includes the DCO.

**Comment by jasnell** [comment]
@nodejs/lts, Here is a draft strawman.. feel free to knock it down:

---
This WG would have the following responsibilities:

* Development and Administration of all LTS policies and release schedules.
* Management of LTS Branches including determination of which commits land and which do not.
* Determining when a Stable branch is ready to migrate into LTS status and submitting the LTS Proposal to the CTC.
* Authoring and editing LTS related documentation within the Node.js project.
* Working with the ecosystem to ensure appropriate stability of LTS releases (smoke-testing); ownership and responsibility for the [citgm](nodejs/citgm) tool
* Advising the CTC and TSC on all LTS related issues and discussions
* Messaging about the future of LTS to give the community advance notice of changes.

**Comment by TheAlphaNerd** [comment]
are we still planning to charter?

**Comment by rvagg** [comment]
OK, strawman proposal: let's not charter and simply let LTS responsibility be a soft-delegation of the CTC which it can intervene in at any time it likes. In practice this group takes responsibility for _versioning_ and branch management, not just LTS, but it's also not needed to have autonomy or the trappings of a full WG, it's really just a team of interested parties who have the time, energy and interest (mostly because of employer interest) in LTS matters. It's not dissimilar to the V8 team which is effectively given almost complete reign over V8 matters except where there's overlap with other concerns.

Thoughts @nodejs/lts?

**Comment by TheAlphaNerd** [comment]
+1 to strawman

**Comment by bnoordhuis** [comment]
Sounds good to me.

**Comment by mikeal** [comment]
I'm a little bit conflicted about this.

On the one hand, it's a bit much to delegate something as large as "all LTS releases" to a sub-group.

At the same time, the people who are doing this work really are the only people qualified to be making these decisions. It's a huge amount of work and the impact of changes will get more difficult to understand by those not doing the merges over time.

Right now the divisions of responsibility this isn't a problem because the CTC is good about delegating and trusting the people in these teams but one of the things that ensures that this continues in the future is guaranteeing autonomy over decisions like this.

We setup these structures to institutionalize some of the cultural norms and precedents we thought were important: like giving those who do the work ownership and autonomy over the work. The good news is that this is working and the culture around delegation is still strong but that could erode over time if we don't continue to institutionalize the values.

**Comment by jasnell** [comment]
I'm ok with chartering as an actual WG but don't really see the pressing need. Definitely wouldn't object to it tho at this point.

**Comment by Fishrock123** [comment]
I think it should probably be an actual WG

**Comment by hbetts** [comment]
As a member of a team that supports Node developers in a corporate environment, I already assume many of the responsibilities listed by @jasnell are supported by the Node CTC, even if on an ad-hoc basis.

I believe, as perhaps @mikeal hinted at, that formalizing a working group around the individuals, and responsibilities, already inherit in the LTS process, would help to demonstrate Node's long-term commitment to stability for corporate users, and ensure the autonomy to continue that process, even if the CTC's own priorities, and resource allocation, shift.
