### ISSUE TITLE
LTS WG Meeting - 2015-11-02 1pm Pacific 

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#53]
Time: 9PM Monday November 2nd UTC (1pm Pacific), or in your local timezone: http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js%20Foundation%20LTS%20Meeting%202015-11-02&iso=20151102T21 **PLEASE NOTE DAYLIGHT SAVING SHIFT FOR SOME TIMEZONES**

**Agenda and minutes** can be collected in here and copied into this repo later: 
https://docs.google.com/document/d/1AKPRkmeKEOVZnvN0698JNNgK1Uw4VTBLMA9oFg-oAQ8 (if you're attending the meeting and don't have write access to this doc please give me your google login email).

Previous minutes: 
https://docs.google.com/document/d/156bztXDR1CoPAU8BzCKCbgU-9IYTprk__aNsd0N1G0Q

**Hangout on air** for active participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYe1gWyx4ZbW2Uyl4oVBMn2ZgRw_viokqpxw5gjFHwnkJr9rfw

**YouTube** feed for observers and saved recording: http://www.youtube.com/watch?v=wfg2nHXAQqI

Current invited participants, this list is not exclusive if you think you should also join:

* @bnoordhuis 
* @dshaw
* @Fishrock123 
* @jasnell 
* @misterdjules 
* @rvagg
* @shigeki
* @trevnorris 
* @geek 
* @mhdawson
* @ofrobots
* @joaocgreis
* @srl295
* @zkat
* @thealphanerd

### nodejs/node

* deps: backport 9da3ab6 from V8 upstream [#3609](https://github.com/nodejs/node/pull/3609)

### nodejs/LTS

* Schedule for v0.10.x and v0.12.x Releases [#52](https://github.com/nodejs/LTS/issues/52)
* tls: make server not use DHE in less than 1014 bits [#49](https://github.com/nodejs/LTS/issues/49)
* Charter this [#48](https://github.com/nodejs/LTS/issues/48)
* npm in 0.10 LTS [#37](https://github.com/nodejs/LTS/issues/37)

Agenda discussion can happen in this thread.

**Comment by zkat** [comment]
Agenda-wise: I'd like to have a discussion about what's considered breaking in re npm -- specifically, we'd like to be able to continue to update and maintain features directly related to our server-side changes: Some parts of npm, such as the installer, `npm version`, etc, either don't interact at all with our servers, or they have significant components that affect users' local experience.

Others, otoh, such as `npm dist-tag` and `npm access`, are simply command-line interfaces to server-side features, exclusively. For things like these, I'd like us to consider allowing semver minor-level changes to be included in LTS, since they are essentially and directly connected to the registry, which is a living application, and not something we can just say "oh yeah build on that version of it" for.

**Comment by yunong** [comment]
Specifically I'd like to discuss https://github.com/nodejs/node/pull/3609. With the long cadence between LTS releases, I'd like to provide feedback on the current LTS release rules, from an enterprise perspective. cc @ofrobots

**Comment by rvagg** [comment]
@jasnell can you check the time for this please? I _think_ it's actually 12 noon Pacific time.

**Comment by TheAlphaNerd** [comment]
I will be making every effort to attend but will be traveling and might not be able to.

**Comment by jasnell** [comment]
@rvagg .. yep, forgot about the switch back to standard time... fixing. It should be 9pm UTC http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js%20Foundation%20LTS%20Meeting%202015-11-02&iso=20151102T21

**Comment by jasnell** [comment]
@nodejs/lts ... the plan last week was to have a follow up LTS meeting this afternoon. Unfortunately I have a conflict that I cannot get out of that came up this morning. I believe we need @zkat on the call and I believe she's still in Japan this week. I propose that we go ahead and push to next week.

**Comment by mhdawson** [comment]
If possible can we find a time this week.  I like to get some closure on:

tls: make server not use DHE in less than 1014 bits #49
