### ISSUE TITLE
LTS Meeting - Monday Nov 23 - 4PM EST

### ISSUE THREAD

**Issue by mhdawson** [nodejs/LTS#58]
James is a away and he asked me to run the meeting today.

He mentioned he was going to send out a recurring meeting but I've not seen it so I'm opening this issue.

Event page: https://plus.google.com/events/c97bmu1q4o0g6fteodudpvln94s

Hangouts link for participants: https://plus.google.com/hangouts/_/hoaevent/AP36tYdbK7VQEIgf8PfFeEkV5dHdCZ3ba2j4e1kR_g-OC3upzhqVWg?hl=en&authuser=0

Link for those who just want to watch: http://youtu.be/_d6nvm_cCgs

**Comment by mhdawson** [comment]
I guess we did not get this out early enough or through the right channels.  It was just me on the meeting.  I think we'll have to try for next week.

**Comment by misterdjules** [comment]
@mhdawson I had setup the original meeting invite with Google calendar, and then I think I removed it accidentally. Without an entry in members' calendars, I'm afraid we'll continue to see people not showing up because they're not reminded of the meeting.

So it seems the next step would be to have someone create that calendar invite again, so that people get notified of the meeting every week.

**Comment by mhdawson** [comment]
Meeting did not happen so just closing
