### ISSUE TITLE
Schedule for LTS Meetings

### ISSUE THREAD

**Issue by jasnell** [nodejs/LTS#6]
What is the schedule for the LTS WG Meetings? We should get this kicked off soon.

**Comment by rvagg** [comment]
I was keen to have one next week but so far haven't started a doodle and my schedule is slightly crazy as I move around the globe. The main blockers here are how busy both myself and @bnoordhuis are currently but this is important enough for ourselves and for our respective companies that we should be able to prioritise this.

There is also some discussion of meeting in https://github.com/iojs/LTS/issues/5 too for reference.

**Comment by jasnell** [comment]
Ok, let me know if there's anything I can do to help facilitate getting things rolling.

**Comment by jasnell** [comment]
Doodle for scheduling: http://doodle.com/37rwvfupsnrawff6
@nodejs/tsc

**Comment by drewfish** [comment]
Are the times in doodle localized? Or are they PDT?

**Comment by jasnell** [comment]
They should be PDT.

**Comment by bnoordhuis** [comment]
Before we commit to a time, is there an agenda?

**Comment by jasnell** [comment]
Ok, so status update on this: @misterdjules suggested yesterday that the Call-Formerly-Known-As-The-Joyent-Node-TC-Weekly-Status-Call (thursday mornings at 9am pst) should transition into the nodejs/LTS call. We'll need to reschedule the time to better fit with @rvagg's schedule and others who are outside the US

**Comment by mikeal** [comment]
Also make sure you record this and we get it up on the soundcloud account :)

**Comment by misterdjules** [comment]
@jasnell Any update on scheduling this call, or should be keep the Thursday/9am PDT time slot for the next one (this Thursday)?

**Comment by misterdjules** [comment]
Now that @shigeki and @joaocgreis are part of joyent/node collaborators, they might want to attend at least some of these meetings, which makes finding a time slot that works across time zones even more important since they are in Japan and Portugal respectively.

@jasnell @rvagg Is 1pm PDT a time slot that turned out to work best for most time zones? If so, then maybe let's see if that time slot works for any day of the week.

**Comment by rvagg** [comment]
Sure, may as well add another 6am to my calendar. Let's do this, thanks @misterdjules!

**Comment by misterdjules** [comment]
Just added @shigeki and @joaocgreis as members of the LTS working group because they are collaborators in joyent/node.

@jasnell @rvagg New doodle here only with the 1pm time slot for every day of the week but Wednesday (there's already the Node.js TSC weekly meeting on that day): http://doodle.com/myb9svwvuuake76x.

@nodejs/lts Please fill out this doodle to let us know about your availability. If none of these time slots work for you, we'll come up with another set of time slots.

**Comment by rvagg** [comment]
Build is in that slot for Tuesday so that puts you and I out for that one for now. I can do any of the other options.

**Comment by misterdjules** [comment]
@rvagg Good point, somehow I had missed that. Doodle edited. Thank you!

**Comment by srl295** [comment]
Slots work for me but not this week ( 22nd is ok)

**Comment by joaocgreis** [comment]
At 1pm PDT I can attend only on Fridays, and even so not always.

I can almost always attend meetings starting between 4am and 10am PDT (lasting until 11), later than that only Wednesdays and Fridays. Feel free to adjust the time as it's best for @shigeki since my input is still quite limited and I can always read the minutes.

**Comment by misterdjules** [comment]
I wanted things to get started so I sent an invite for a meeting every Monday at 1pm PDT. @shigeki, is it a time that could work at least sometimes? We'll need your input on security related topics. We can always work from the minutes though.

@joaocgreis I hope we can find a timing that works in the near future for you. As for @shigeki, in the meantime the minutes will allow you to follow what's being discussed in these meetings.

If nobody has any major concern, then I suggest we start meeting this week, and move the joyent/node weekly call meeting to this one.

**Comment by trevnorris** [comment]
Works for me.

**Comment by mhdawson** [comment]
Ok with me as well

**Comment by misterdjules** [comment]
@trevnorris @mhdawson Thank you!

If anybody wants to be part of the meetings and did not receive an invitation, please let me know.

Also, I've been trying to maintain an accurate list of people interested in LTS releases as the @nodejs/lts team. If you're not a member of this team and would like to participate in the LTS effort, please let me know too.

**Comment by Fishrock123** [comment]
I'm interested in joining for now in light of the release proposals set forth in https://github.com/nodejs/io.js/issues/1997 and how LTS may interact in our current processes and potential future processes.

**Comment by drewfish** [comment]
I'm interested in the minutes. Will they be published in this repo (as an issue, wiki, ...) ?

**Comment by misterdjules** [comment]
@drewfish Yes, they will be published. I would suggest to do that as a PR that gets merged into the repository's content, but that will need to be discussed too.

**Comment by joaocgreis** [comment]
It is a difficult time for me, but I'll attend when possible. Next Monday I can't make it. Thanks @misterdjules !

**Comment by misterdjules** [comment]
@Fishrock123 You've been added to the meeting invitation, thank you for the interest!

**Comment by misterdjules** [comment]
@Fishrock123 Also added you to the list of members of the @nodejs/lts team.

**Comment by misterdjules** [comment]
Closing this issue as we have our first meeting Monday June 29th 2015, and this meeting repeats every week.

**Comment by Fishrock123** [comment]
I don't think I'll actually make it to this, I'll probably be on the road.
