### ISSUE TITLE
Where is the official node.js LTS schedule?

### ISSUE THREAD

**Issue by majgis** [nodejs/LTS#66]
It is not clear to me what the LTS schedule is for v0.12

On this page, https://github.com/nodejs/LTS, the chart doesn't match the table, and the table is under a section that says "hypothetically".  

I expected to find this information on the main nodejs.org site but I did not find it.  Where  is the gospel truth?

**Comment by rvagg** [comment]
It's only "hypothetical" because it uses actual version numbers and this was done before we had any of those numbers. We need to update it to remove "hypothetical" because we now know how 4.x turned out.

The dot-points are the authoritative source of the policy with the chart attempting to display that graphically.

We should leave this open as a TODO to fix up the README. I've had some ideas about how to clear it up to try and remove some of the confusion.

**Comment by ChALkeR** [comment]
@rvagg The confusing part of it is that the table states that 0.12 LTS End is 2017-04-01, while the chart has 2016-12. Which one is correct? Also note that #36 states that 0.12 LTS End is 2016-12-31.

**Comment by rvagg** [comment]
argh, yeah, the chart is correct, we pulled 0.12 to the end of 2016 to line up with the corresponding OpenSSL EOL. 0.12 is EOL on 2016-12-31.

I'll fix it asap, not today cause :zzz:

**Comment by TheAlphaNerd** [comment]
The schedule is now public. Closing
